(defun cadr (lst) (car (cdr lst)))
(defun nth (n lst) (if (<= n 0) (car lst) (nth (- n 1) (cdr lst))))
(defun concatenate (&rest args) (+ args))
(defun length (lst)
    (if
        (null lst)
            0
            (+ (length (cdr lst)) 1)
        )
    )
(defmacro my-and (&rest expr)
    (begin
    (print expr)
    (cond
        ((null expr) (print "emptylist") t)
        ((null (cdr expr)) (print "one element") ,(car expr))
        (else `(if ,(car expr) (my-and ,@(cdr expr)))
        )
    ))
)
(defmacro my-cond (&rest branches)
    (if (null branches)
        nil
        (let (
                (part-1 (car branches))
                (last (cdr branches))
                (condition (car part-1))
                (body (cdr part-1))
            )
            `(if ,condition (begin ,@body)
                (my-cond ,@last)

            )
        )
    )
)
(defmacro when (condition &rest body)
    `(if ,condition (begin ,@body ) nil)
)
(defmacro unless (condition &rest body)
    `(if (not ,condition) (begin ,@body) nil)
)
