controls(
viewTypeUnits(
;( viewType                userUnit        DBUPerUU )
;( --------                     --------           -- --------   )
  ( maskLayout		 micron 	1000	)
  ( schematic		 inch 	160	)
  ( schematicSymbol	 inch 	160	)
  ( netlist		 inch 	160	)
) ;viewTypeUnits

  mfgGridResolution(
    ( 0.001 )
  ) ;mfgGridResolution

) ;controls

layerDefinitions(
 techPurposes(
;( purposeName  purposeNum  abbreviation )
;(   -----------        ----------        ----------     )
( corner         1          crnr          )
( struct         3          strct         )
 ) ;techPurposes

 techLayers(
;( layerName  layerNum   abbreviation )
;(   ---------      --------      ------------ )
(   note             0    note        )
(   M01              1    m01         )
(   M02              2    m02         )
(   M03              3    m03         )
(   M10              4    m10         )
(   M15              5    m15         )
(   M16              6    m16         )
(   M17              7    m17         )
(   M18              8    m18         )
(   M19_passivation  9    passivation )
(   M20_tme          26   tme         )
(   M23             10    m23         )
(   M29_cut         11    cut         )
(   M31_metal1      12    metal1      )
(   M32_via         13    via         )
(   M33_metal2      14    metal2      )
(   M38_metal3      15    metal3      )
(   M39_via2        16    via2        )
(   M42_tin         27    tin         )
(   M43_pad         28    pad         )
(   M55             17    m55         )
(   M58_tinvia      29    tinvia      )
(   M60             18    m60         )
(   M72             19    m72         )
(   M76             20    m76         )
(   M86_rough       30    rough       )
(   M107            31    m107        )
(   M133            32    m133        )
(   M138            21    m138        )
(   M189            33    m189        )
(   M212_poly0      22    poly0       )
(   M235_s1         23    s1          )
(   M250            24    m250        )
(   M256            25    m256        )
) ;techLayers

 techLayerPurposePriorities(
;(  layerName   purposeName  )
;(   ---------        ------------     )
(   M01             drawing   )
(   M02             drawing   )
(   M03             drawing   )
(   M10             drawing   )
(   M15             drawing   )
(   M16             drawing   )
(   M17             drawing   )
(   M18             drawing   )
(   M19_passivation drawing   )
(   M20_tme         drawing   )
(   M23             drawing   )
(   M29_cut         drawing   )
(   M31_metal1      drawing   )
(   M32_via         drawing   )
(   M33_metal2      drawing   )
(   M38_metal3      drawing   )
(   M39_via2        drawing   )
(   M42_tin         drawing   )
(   M43_pad         drawing   )
(   M55             drawing   )
(   M58_tinvia      drawing   )
(   M60             drawing   )
(   M72             drawing   )
(   M76             drawing   )
(   M86_rough       drawing   )
(   M107            corner    )
(   M107            all       )
(   M138            drawing   )
(   M189            struct    )
(   M212_poly0      drawing   )
(   M235_s1         drawing   )
(   M250            drawing   )
(   M256            drawing   )
(   note            drawing   )
) ;techLayerPurposePriorities

techDisplays(
;(lLayerName purposeName  packet  vis sel   con2ChgLy   drgEnbl  valid )
;(   ---------        -------           ------   --- ---    ------------     -------    ----- )
(   M01             drawing   defaultPacket           t t t t t   )
(   M02             drawing   defaultPacket           t t t t t   )
(   M03             drawing   defaultPacket           t t t t t   )
(   M10             drawing   defaultPacket           t t t t t   )
(   M15             drawing   defaultPacket           t t t t t   )
(   M16             drawing   defaultPacket           t t t t t   )
(   M17             drawing   defaultPacket           t t t t t   )
(   M18             drawing   defaultPacket           t t t t t   )
(   M19_passivation drawing   P_polyimid_drawing      t t t t t   )
(   M20_tme         drawing   defaultPacket           t t t t t   )
(   M23             drawing   defaultPacket           t t t t t   )
(   M29_cut         drawing   P_cut_drawing           t t t t t   )
(   M31_metal1      drawing   P_metal1_drawing        t t t t t   )
(   M32_via         drawing   P_via_drawing           t t t t t   )
(   M33_metal2      drawing   P_metal2_drawing        t t t t t   )
(   M38_metal3      drawing   P_metal3_drawing        t t t t t   )
(   M39_via2        drawing   P_via2_drawing          t t t t t   )
(   M42_tin         drawing   defaultPacket           t t t t t   )
(   M43_pad         drawing   defaultPacket           t t t t t   )
(   M55             drawing   defaultPacket           t t t t t   )
(   M58_tinvia      drawing   defaultPacket           t t t t t   )
(   M60             drawing   defaultPacket           t t t t t   )
(   M72             drawing   defaultPacket           t t t t t   )
(   M76             drawing   defaultPacket           t t t t t   )
(   M86_rough       drawing   defaultPacket           t t t t t   )
(   M107            corner    defaultPacket           t t t t t   )
(   M107            all       defaultPacket           t t t t t   )
(   M138            drawing   defaultPacket           t t t t t   )
(   M189            struct    defaultPacket           t t t t t   )
(   M212_poly0      drawing   P_poly0_drawing         t t t t t   )
(   M235_s1         drawing   P_p2c_drawing           t t t t t   )
(   M250            drawing   defaultPacket           t t t t t   )
(   M256            drawing   defaultPacket           t t t t t   )
(   note            drawing   P_note_drawing          t t t t t   )
) ;techDisplays

) ;layerDefinitions

layerRules(
 functions(
;( layer     function     [maskNumber])
;( -----      --------        ------------    )
( M212_poly0            poly          212 )
( M29_cut               cut           29  )
( M31_metal1            metal         31  )
( M32_via               cut           32  )
( M33_metal2            metal         33  )
( M39_via2              cut           39  )
( M38_metal3            metal         38  )
( M42_tin               metal         42  )
( M58_tinvia            cut           58  )
 ) ;functions

 mfgResolutions(
;( layer         mfgResolution )
;( -----           -------------    )
(   note            0.001 )
(   M01             0.001 )
(   M02             0.001 )
(   M03             0.001 )
(   M10             0.001 )
(   M15             0.001 )
(   M16             0.001 )
(   M17             0.001 )
(   M18             0.001 )
(   M19_passivation 0.001 )
(   M20_tme         0.001 )
(   M23             0.001 )
(   M29_cut         0.001 )
(   M31_metal1      0.001 )
(   M32_via         0.001 )
(   M33_metal2      0.001 )
(   M38_metal3      0.001 )
(   M39_via2        0.001 )
(   M42_tin         0.001 )
(   M43_pad         0.001 )
(   M55             0.001 )
(   M58_tinvia      0.001 )
(   M60             0.001 )
(   M72             0.001 )
(   M76             0.001 )
(   M86_rough       0.001 )
(   M107            0.001 )
(   M138            0.001 )
(   M189            0.001 )
(   M212_poly0      0.001 )
(   M235_s1         0.001 )
(   M250            0.001 )
(   M256            0.001 )
) ;mfgResolutions

) ;layerRules

